### ISSUE TITLE
add command front-matter deep merge

### ISSUE THREAD

**Issue by MarcLoupias** [MarcLoupias/md-file-converter#20]
**Problem:** 

There is no include for yaml. It is a pain to manage front-matter in a large markdown file set where a lot of values are the same from a file to another.

**Solution:**

Add a command utility to apply values from a yaml file to a set of markdown files. If a markdown file have no front-matter, create it with the values provided in the yaml.

**Impl**

Merging with `Object.assign` or the spread operator is doing only a shallow merge, not a deep merge.

It could be very nice to support deep merge to update a value deep in a tree on a file set.

For example to update [a css file path for that case](https://github.com/MarcLoupias/mdfc-map-to-html/issues/5).

The yaml tree could be : 

```yaml
htmlHead:
    title: 'uber title for uber document'
    links:
        - href: mobile.css
          rel: stylesheet
          media: all
        - href: print.css
          rel: stylesheet
          media: print
        - href: desktop.css
          rel: stylesheet
          media: 'screen and (min-width: 600px)'
        - href: favicon32.png
          rel: icon
        - href: favicon72.png
          rel: apple-touch-icon-precomposed
          sizes: 72x72
    meta:
        - name: description
          content: 'my uber document'
        - name: viewport
          content: 'width=device-width, initial-scale=1, minimal-ui'
        - property: 'og:type'
          content: website
```

And we could want to update only the print.css to printer.css in each concerned markdown file with a yaml like that : 

```yaml
htmlHead:
    links:
        - href: printer.css
```

without modifying the rest of the tree.

Needs to check how to select the right link in that case, by adding a selector in the CLI command ?

See :
- [JavaScript Deep Merge](https://davidwalsh.name/javascript-deep-merge)
- [TehShrike/deepmerge](https://github.com/TehShrike/deepmerge)
- [How to deep merge instead of shallow merge? - stackoverflow.com](https://stackoverflow.com/questions/27936772/how-to-deep-merge-instead-of-shallow-merge)
